### PR TITLE
Fundamental constants

### LINKED ISSUE #160: +Value of Planck Constant
*Issue migrated from trac ticket # 5779*

**component:** unit definitions | **priority:** major

#### 2021-01-15 03:48:52: simon.cox@csiro.au created the issue

___
> The CODATA 2017 value is 
> 
> 6.62607015E−34 J.s
> 
> Table 3. in https://iopscience.iop.org/article/10.1088/1681-7575/aa950a/pdf

### PR DESCRIPTION
**Pull request by dr-shorthair**
Update values for 7 fundamental constants to align with 2018 revision from CODATA & NIST
Fixes #160 #161 #162 #230 #231 #232 #233

### CODE REVIEW

**Comment by chgessner** [comment]
Let us please start a discussion how to implement this change in a way that reflects the 2019 redefinition of the SI base units. This includes adding the three missing "defining constants", which now have fixed precise values, together with their definitions in the "value" part:
* Avogadro constant, proposed symbol: [N_A]
* ground state [hyperfine structure transition frequency of the caesium-133 atom, proposed symbol [nu_Cs] or [delta_nu_Cs]
* luminous efficacy, proposed symbol. [K_cd]

Also update the numerical value of c velocity of light, symbol c.

This does not change the fact that all SI units are still derived from the (seven) SI base units, but it is required for the sake of completeness. We can discuss, if there should be some kind of label to discriminate "precise constants" from "experimental constants", the latter having a numerical value that may change over time.

Christof

**Comment by gschadow** [comment]
@chgessner said:
> Let us please start a discussion how to implement this change in a way that reflects the [2019 redefinition of the SI base units](https://en.wikipedia.org/wiki/2019_redefinition_of_the_SI_base_units). 

Very intriguing. Maybe we don't even need to make a separate issue out of this as it relates to the question of the constants and how the numerical values of these constants are going to be maintained in the future.

Now how to we practically proceed.

I think we probably should proceed in 2 steps. First would be to actually wave this through for a next "soon-ish" release of UCUM. That very release management seems to be stuck in endless ruminations on what the current trend among the mythical "developer" is, so perhaps we'll have the constants figured out before doing a new release.

As for updating the constants, I just found text in the specification that also needs updated to specify what our source of these constants is now and what it will be in the (near) future. The text right under the Table 6 of §32 currently is:

> This list is not complete. It does not list all constants but only those that are fundamental and from which many other constants can be derived. The source of this table is The NIST Reference on Constants, Units, and Uncertainty Version 2.1, 21 May 1998. NIST Physics Laboratory. http://physics.nist.gov/cuu/Constants/index.html

That reference to physics.nist.gov is still active, and has (for example) Planck's constant as 6.62607015  x 10-34 J Hz-1 when it was 6.6260755 in the current release of UCUM, and is now proposed as 6.62607015. So it looks like our reference to the site would still be good and all we need to do is update the values and in the text we say Version 2.1, 21 May 1998 which we should change to reference whatever "version number" is the 2018 revision we now use.

The big discussion that Christof brings up probably should go into a new ticket. I put it into the #255 harmonization discussion for now.

**Comment by dr-shorthair** [comment]
I already proposed changes to the text under Table 6 - see the diffs and https://github.com/ucum-org/ucum/pull/242/commits/c115895cfcb366d0bc09c4bfcabde9378087eb20

**Comment by timbrisc** [comment]
@dr-shorthair I appreciate your effort on this. The decision was made to follow a strict workflow where updates are made in individual pull requests so that reviewers can have a granular look at the changes for validation. I will be closing this PR in favor of that separate work.

**Pull request closed without merging**
